#!/usr/bin/env python3
"""Compile station.yaml into weewx.conf + skin.conf + generated user/*.py modules.

Run inside the weewx container; configobj/yaml/weewx are baked in:

    docker compose run --rm --entrypoint python weewx /configure.py

Reads:
  /station.yaml  (the one source of configurable truth; secrets stay in .env)

Writes:
  /data/weewx.conf
  /data/skins/Bootstrap/skin.conf
  /data/bin/user/extra_obs.py     (only if `observations:` / `units.custom_groups:` set)
  /data/bin/user/extra_schema.py  (only if `schema:` set)

Env overrides (overlay-controlled, not user-edited config):
  WEEWX_DRIVER     (mqtt | simulator)        — set by docker-compose.demo.yml
  WEEWX_WS_URL     (ws/wss URL)              — set by prod overlay to wss://$DOMAIN
  MQTT_WEEWX_USER  MQTT_WEEWX_PASS           — broker creds for driver + publish
  MQTT_DASH_USER   MQTT_DASH_PASS            — read-only creds embedded in skin

The file is organised as one `apply_<section>(...)` per top-level YAML key,
called from `main()`. Phase 2/3 will plug in `apply_dashboard`, `apply_branding`,
`apply_logging`, `apply_services` -- the data flow is the same shape.
"""
import os
import shutil
import sys

import configobj
import yaml
import weewx.units

CONF = "/data/weewx.conf"
SKIN = "/data/skins/Bootstrap/skin.conf"
SKIN_DIR = "/data/skins/Bootstrap"
USER_DIR = "/data/bin/user"
EXTRA_OBS = os.path.join(USER_DIR, "extra_obs.py")
EXTRA_SCHEMA = os.path.join(USER_DIR, "extra_schema.py")
EXTENSIONS_PY = os.path.join(USER_DIR, "extensions.py")
EXT_HOOK_BEGIN = "# --- BEGIN station.yaml extra_obs hook (managed by configure.py) ---"
EXT_HOOK_END = "# --- END station.yaml extra_obs hook ---"

# Bind-mounted from the project root (see docker-compose.yml weewx volumes).
BRANDING_DIR = "/branding"
USER_DIR_SRC = "/user"

STATION_YAML = os.environ.get("STATION_YAML", "/station.yaml")
USE_SIMULATOR = os.environ.get("WEEWX_DRIVER", "mqtt").strip().lower() in ("simulator", "sim")
# WEEWX_WS_URL (overlay-controlled) wins over station.yaml's mqtt.websocket_url.
WS_URL_ENV = os.environ.get("WEEWX_WS_URL", "").strip()
MQTT_WEEWX_USER = os.environ.get("MQTT_WEEWX_USER", "")
MQTT_WEEWX_PASS = os.environ.get("MQTT_WEEWX_PASS", "")
MQTT_DASH_USER = os.environ.get("MQTT_DASH_USER", "")
MQTT_DASH_PASS = os.environ.get("MQTT_DASH_PASS", "")

GENERATED_HEADER = (
    "# Generated by configure.py from station.yaml -- DO NOT EDIT BY HAND.\n"
    "# Re-running configure.py (or `./setup.sh` on a fresh ./data) regenerates it.\n"
)


# ─── small helpers ──────────────────────────────────────────────────────────

def load_yaml(path):
    try:
        with open(path) as h:
            return yaml.safe_load(h) or {}
    except FileNotFoundError:
        sys.exit(f"configure.py: station.yaml not found at {path}")


def ensure_in_list(section, key, value):
    """Make sure `value` is in a configobj list-or-scalar option."""
    cur = section.get(key, [])
    if isinstance(cur, str):
        cur = [cur] if cur else []
    else:
        cur = list(cur)
    if value not in cur:
        cur.append(value)
    section[key] = cur


def remove_from_list(section, key, value):
    """Remove `value` from a configobj list-or-scalar option, if present."""
    cur = section.get(key, [])
    if isinstance(cur, str):
        cur = [cur] if cur else []
    else:
        cur = list(cur)
    section[key] = [v for v in cur if v != value]


def remove_if_exists(path):
    if os.path.exists(path):
        os.remove(path)


# ─── section handlers ──────────────────────────────────────────────────────

def apply_station(c, station):
    """[Station] + [StdArchive]: identity + interval. Driver picked by env (demo overlay)."""
    s = c.setdefault("Station", {})
    s["location"] = str(station.get("location", "Sailing Center"))
    s["latitude"] = str(station.get("latitude", "37.808"))
    s["longitude"] = str(station.get("longitude", "-122.409"))
    alt = station.get("altitude") or {"value": 3, "unit": "foot"}
    # Written as a configobj list `3, foot` (NOT a quoted string -- StdQC and
    # WeeWX's parser handle the list form correctly).
    s["altitude"] = [str(alt.get("value", 3)), str(alt.get("unit", "foot"))]
    # Demo overlay sets WEEWX_DRIVER=simulator; default = real MQTTSubscribe driver.
    s["station_type"] = "Simulator" if USE_SIMULATOR else "MQTTSubscribeDriver"

    arc = c.setdefault("StdArchive", {})
    arc["archive_interval"] = str(station.get("archive_interval", 60))
    arc["record_generation"] = "software"


def apply_mqtt_and_sensors(c, mqtt_cfg, sensors_cfg):
    """[MQTTPublish] (loop -> weather/loop) + [MQTTSubscribeDriver] (rtl_433 ingest).

    Combined so both can share the broker host/port without ordering coupling.
    """
    broker = str(mqtt_cfg.get("broker", "mqtt"))
    port = str(mqtt_cfg.get("port", 1883))

    # [MQTTPublish]: stream every loop packet as JSON to weather/loop. The
    # default unit_system + append_unit_label produce gauge-ready keys
    # (outTemp_F, windSpeed_mph, ...) matching the fuzzy-archer skin.
    c["MQTTPublish"] = {
        "enable": "true",
        "host": broker,
        "port": port,
        "protocol": "MQTTv311",
        "topics": {
            "weather/loop": {
                "publish": "true",
                "type": "json",
                "binding": "loop",
                "unit_system": "US",
                "append_unit_label": "true",
            },
        },
    }

    # [MQTTSubscribeDriver]: translate sensors.sources into the topics map.
    topics = {"unit_system": str(sensors_cfg.get("unit_system", "US"))}
    errors = []
    for sensor in sensors_cfg.get("sources", []) or []:
        name = sensor.get("name", "?")
        topic = sensor.get("topic")
        if not topic:
            errors.append(f"sensor '{name}': missing 'topic'")
            continue
        # Default ON: rtl_433 payloads always carry string metadata (model, mic,
        # protocol, ...) that MQTTSubscribe can't floatify and would otherwise
        # use to reject the whole message. Set `ignore_unmapped: false` to
        # process every field.
        opt_out = bool(sensor.get("ignore_unmapped", True))

        section = {"message": {"type": "json"}}
        if opt_out:
            section["ignore"] = "true"
        if sensor.get("msg_id_field"):
            section["msg_id_field"] = str(sensor["msg_id_field"])

        for field, spec in (sensor.get("fields") or {}).items():
            spec = spec or {}
            entry = {}
            if opt_out:
                entry["ignore"] = "false"          # opt this field back in
            wx_name = spec.get("name", field)
            entry["name"] = wx_name
            if "units" in spec:
                units = spec["units"]
                if units not in weewx.units.conversionDict:
                    errors.append(f"sensor '{name}', field '{field}': unknown units '{units}'")
                elif wx_name not in weewx.units.obs_group_dict:
                    errors.append(f"sensor '{name}', field '{field}': '{wx_name}' "
                                  "is not a known WeeWX observation (can't apply units)")
                else:
                    entry["units"] = units
            if spec.get("contains_total"):
                entry["contains_total"] = "true"
            section[field] = entry
        topics[topic] = section

    if errors:
        sys.exit("station.yaml sensors errors:\n  - " + "\n  - ".join(errors))

    c["MQTTSubscribeDriver"] = {
        "driver": "user.mqttsubscribe",
        "host": broker,
        "port": port,
        "topics": topics,
    }
    c.pop("MQTTSubscribeService", None)

    # Engine services: keep publish (RESTful), drop the subscribe *service*
    # entry the installer added (we use it as the DRIVER, not a service).
    svc = c.setdefault("Engine", {}).setdefault("Services", {})
    remove_from_list(svc, "data_services", "user.mqttsubscribe.MQTTSubscribeService")
    ensure_in_list(svc, "restful_services", "user.mqttpublish.PublishWeeWX")


def apply_credentials(c):
    """Wire MQTT creds from the env (.env) into driver + publish sections."""
    if MQTT_WEEWX_PASS:
        for section in ("MQTTSubscribeDriver", "MQTTPublish"):
            c[section]["username"] = MQTT_WEEWX_USER
            c[section]["password"] = MQTT_WEEWX_PASS


def apply_qc(c, qc):
    """[StdQC][[MinMax]]: per-observation min/max bounds (with optional unit).

    Values are written as configobj lists so they emit unquoted -- a quoted
    `"min, max, unit"` would be mis-parsed by StdQC at runtime.
    """
    if not qc:
        return
    mm = c.setdefault("StdQC", {}).setdefault("MinMax", {})
    for obs, bounds in qc.items():
        out = [str(bounds["min"]), str(bounds["max"])]
        if "unit" in bounds:
            out.append(str(bounds["unit"]))
        mm[obs] = out


def apply_units(c, units):
    """[StdConvert][Group]: force display unit per group.

    `custom_groups` (defining brand-new unit groups) is written into
    `extra_obs.py` instead of weewx.conf -- see apply_observations().
    """
    if not units:
        return
    groups = units.get("groups") or {}
    if groups:
        g = c.setdefault("StdConvert", {}).setdefault("Group", {})
        for grp, unit in groups.items():
            g[grp] = str(unit)


def apply_labels(c, labels):
    """[StdReport][[Defaults]][[[Labels]]][[[[Generic]]]]: per-obs display labels.

    The skin's `$Labels` template variable is built from skin lang.conf merged
    with the REPORT-scoped [StdReport][[Defaults]] / [StdReport][<report>]
    overrides; a top-level [Labels] section in weewx.conf is NOT merged into
    that scope and the skin ignores it. Putting labels under [Defaults] makes
    them apply to every report (matches what fuzzy-archer / mast-buoy expect
    so they land in weewxData.json's `labels.Generic`).

    Idempotent: clears the managed [[[[Generic]]]] block and rebuilds it. Also
    strips any legacy top-level [Labels] block from prior runs.
    """
    c.pop("Labels", None)                         # drop the old (broken) location
    defaults = c.setdefault("StdReport", {}).setdefault("Defaults", {})
    if not labels:
        labs = defaults.get("Labels")
        if labs:
            labs.pop("Generic", None)
            if not labs:
                defaults.pop("Labels", None)
        return
    labs = defaults.setdefault("Labels", {})
    gen = labs.setdefault("Generic", {})
    gen.clear()
    for obs, label in labels.items():
        gen[obs] = str(label)


def _set_extensions_hook(enabled):
    """Idempotently add/remove `import user.extra_obs` (with marker comments) in
    user/extensions.py. That file is imported by the weewx engine BEFORE the
    driver loads, so registrations fire in time for MQTTSubscribe to validate
    custom-obs fields. Without this, even with extra_obs.py written, the driver
    would init before the service loads and reject the custom obs as unknown.
    """
    if not os.path.exists(EXTENSIONS_PY):
        return                                    # baked template missing -- nothing to do
    with open(EXTENSIONS_PY) as f:
        src = f.read()
    # Strip any previous hook so we re-apply cleanly.
    if EXT_HOOK_BEGIN in src and EXT_HOOK_END in src:
        before, _, rest = src.partition(EXT_HOOK_BEGIN)
        _, _, after = rest.partition(EXT_HOOK_END)
        # Drop the trailing newline that was paired with EXT_HOOK_END.
        src = before.rstrip() + ("\n" + after.lstrip("\n") if after.strip() else "\n")
    if enabled:
        block = (
            "\n" + EXT_HOOK_BEGIN + "\n"
            "# Loaded early (before driver init) so observations/custom unit groups\n"
            "# declared in station.yaml are registered when the driver validates fields.\n"
            "import user.extra_obs  # noqa: F401\n"
            + EXT_HOOK_END + "\n"
        )
        src = src.rstrip() + block
    with open(EXTENSIONS_PY, "w") as f:
        f.write(src)


def apply_observations(observations, custom_groups):
    """Write user/extra_obs.py registering obs_group_dict + (optional) custom unit groups.

    Also updates the IN-PROCESS weewx.units dicts so a subsequent apply_*sensors*
    call's validator (which checks `wx_name in weewx.units.obs_group_dict`) sees
    the new observation names -- otherwise the user couldn't add a custom obs
    and reference it from sensors: in the same station.yaml.

    And adds a hook in user/extensions.py to `import user.extra_obs` so the
    registrations fire at engine startup, before the driver loads. Without that
    the driver would init first and reject the custom obs as unknown at RUNTIME
    even though configure.py validation passes.

    Returns True if a service entry should be wired (always True when present).
    """
    if not observations and not custom_groups:
        remove_if_exists(EXTRA_OBS)
        _set_extensions_hook(False)
        return False

    lines = [GENERATED_HEADER,
             "import weewx.units\n",
             "from weewx.engine import StdService\n",
             "\n"]
    # Custom unit groups first (so per-obs registrations below can reference them).
    sys_map = {"US": "USUnits", "Metric": "MetricUnits", "MetricWX": "MetricWXUnits"}
    for grp, units in (custom_groups or {}).items():
        # units may be a dict {US: dBm, Metric: dBm, MetricWX: dBm} or a single str.
        if isinstance(units, str):
            units = {"US": units, "Metric": units, "MetricWX": units}
        for system, unit in units.items():
            attr = sys_map[system]
            lines.append(f"weewx.units.{attr}[{grp!r}] = {unit!r}\n")
            # Register in-process too so the sensors validator accepts this group.
            getattr(weewx.units, attr)[grp] = unit
    for obs in observations or []:
        lines.append(
            f"weewx.units.obs_group_dict[{obs['name']!r}] = {obs['group']!r}\n"
        )
        weewx.units.obs_group_dict[obs["name"]] = obs["group"]
    # Tiny no-op StdService so weewx.conf can list it under prep_services and
    # the module gets loaded (which is what runs the registrations above).
    lines += [
        "\n",
        "class ExtraObservations(StdService):\n",
        "    \"\"\"Loader for the obs_group/unit registrations above.\"\"\"\n",
        "    def __init__(self, engine, config_dict):\n",
        "        super().__init__(engine, config_dict)\n",
    ]
    os.makedirs(USER_DIR, exist_ok=True)
    with open(EXTRA_OBS, "w") as f:
        f.writelines(lines)
    _set_extensions_hook(True)
    return True


def apply_extra_obs_service(c, enable):
    """Wire user.extra_obs.ExtraObservations into prep_services (or remove it)."""
    svc = c.setdefault("Engine", {}).setdefault("Services", {})
    if enable:
        ensure_in_list(svc, "prep_services", "user.extra_obs.ExtraObservations")
    else:
        remove_from_list(svc, "prep_services", "user.extra_obs.ExtraObservations")


def apply_schema(c, schema_cfg):
    """Optional custom DB schema. Generates user/extra_schema.py = base + extras."""
    if not schema_cfg:
        remove_if_exists(EXTRA_SCHEMA)
        # Reset binding to the stock schema if a previous run had pointed it at extra_schema.
        b = c.setdefault("DataBindings", {}).setdefault("wx_binding", {})
        if b.get("schema", "").startswith("user.extra_schema"):
            b["schema"] = "schemas.wview_extended.schema"
        return

    base = str(schema_cfg.get("extends", "wview_extended"))
    extras = list(schema_cfg.get("extra_columns") or [])
    if not extras:
        sys.exit("station.yaml schema: extra_columns must be a non-empty list (omit `schema:` to use the stock schema)")

    lines = [GENERATED_HEADER,
             f"# Extends weewx's built-in `{base}` schema with the columns below.\n",
             "\n",
             "# Support both pip-installed weewx (weewx.schemas) and the weectl-style\n",
             "# layout where schemas live at /data/bin/schemas (alongside /data/bin/user).\n",
             "try:\n",
             f"    from weewx.schemas.{base} import table as _base_table, day_summaries as _base_summaries\n",
             "except ImportError:\n",
             f"    from schemas.{base} import table as _base_table, day_summaries as _base_summaries\n",
             "\n",
             "_extras = [\n"]
    for col in extras:
        lines.append(f"    ({col!r}, 'REAL'),\n")
    lines += [
        "]\n",
        "\n",
        "table = list(_base_table) + _extras\n",
        "day_summaries = list(_base_summaries) + [(c[0], 'scalar') for c in _extras]\n",
        "schema = {'table': table, 'day_summaries': day_summaries}\n",
    ]
    os.makedirs(USER_DIR, exist_ok=True)
    with open(EXTRA_SCHEMA, "w") as f:
        f.writelines(lines)
    # Point the default binding at the generated module.
    c.setdefault("DataBindings", {}).setdefault("wx_binding", {})["schema"] = "user.extra_schema.schema"


def apply_reports(c):
    """[StdReport]: enable only fuzzy-archer (Bootstrap), into public_html."""
    rep = c.setdefault("StdReport", {})
    rep["HTML_ROOT"] = "public_html"
    for _name, sec in list(rep.items()):
        if isinstance(sec, dict) and sec.get("skin") in ("Seasons", "Standard"):
            sec["enable"] = "false"
    boot = rep.setdefault("Bootstrap", {})
    boot["skin"] = "Bootstrap"
    boot["enable"] = "true"
    boot["lang"] = "en"
    boot["HTML_ROOT"] = "public_html"


# ─── dashboard (fuzzy-archer skin overrides, written under [StdReport][[Bootstrap]]) ───

def _conv(v):
    """YAML value -> configobj-friendly form (booleans become true/false strings,
    lists pass through as configobj lists, None becomes the literal string 'None')."""
    if v is None:
        return "None"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, list):
        return [_conv(x) for x in v]
    return str(v)


def _passthrough(section, src, skip=()):
    """Copy a YAML dict into a configobj section, value-translated."""
    if not src:
        return
    for k, v in src.items():
        if k in skip or isinstance(v, dict):    # skip nested dicts (handled by callers)
            continue
        section[k] = _conv(v)


def _replace_section(boot, name):
    """Clear-and-rebuild helper: pop existing subsection, return a fresh one."""
    boot.pop(name, None)
    return boot.setdefault(name, {})


def _items_section(boot, name, key, items):
    """Helper: emit a `[[[<name>]]] <key> = a, b, c` subsection from a list.
    Removes the subsection entirely if items is None (so re-runs are idempotent)."""
    if items is None:
        boot.pop(name, None)
        return
    _replace_section(boot, name)[key] = [str(x) for x in items]


def _emit_stats(boot, stats):
    if not stats:
        boot.pop("Stats", None)
        return
    s = _replace_section(boot, "Stats")
    if "items" in stats:
        s["stats_items"] = [str(x) for x in stats["items"]]
    for obs, agg_list in (stats.get("aggregations") or {}).items():
        obs_s = s.setdefault(obs, {})
        for agg in agg_list:
            obs_s.setdefault(agg, {})


def _emit_history(boot, history):
    if not history:
        boot.pop("HistoryReport", None)
        return
    s = _replace_section(boot, "HistoryReport")
    if "items" in history:
        s["history_items"] = [str(x) for x in history["items"]]


def _emit_news(boot, news):
    """[[[News]]] -- one [[[[<title>]]]] subsection per entry."""
    if not news:
        boot.pop("News", None)
        return
    s = _replace_section(boot, "News")
    for entry in news:
        title = entry.get("title") or entry.get("date") or entry.get("header") or "untitled"
        e = s.setdefault(str(title), {})
        for k in ("header", "body"):
            if k in entry:
                e[k] = str(entry[k])
        # `img:` may be a dict {src, alt, title} or a bare string (src only).
        img = entry.get("img")
        if isinstance(img, dict):
            for k_yaml, k_conf in (("src", "img_src"), ("alt", "img_alt"), ("title", "img_title")):
                if k_yaml in img:
                    e[k_conf] = str(img[k_yaml])
        elif isinstance(img, str):
            e["img_src"] = img


def _emit_live_gauges(boot, gauges_cfg):
    """[[[LiveGauges]]] live_gauge_items + per-obs subsections.

    YAML: { items: [...], gauges: { <obs>: { payload_key, range: {min,max,splitnumber},
            style: {<any fuzzy-archer key>: value} } } }.
    """
    if not gauges_cfg:
        boot.pop("LiveGauges", None)
        return
    s = _replace_section(boot, "LiveGauges")
    gauges = gauges_cfg.get("gauges") or {}
    items = gauges_cfg.get("items") or list(gauges.keys())
    s["live_gauge_items"] = [str(x) for x in items]
    # Top-level options (heatMapEnabled, animation, ...) at the gauges level.
    _passthrough(s, gauges_cfg, skip=("items", "gauges"))
    for obs, spec in gauges.items():
        g = s.setdefault(obs, {})
        if "payload_key" in spec:
            g["payload_key"] = str(spec["payload_key"])
        for yaml_k, conf_k in (("min", "minvalue"), ("max", "maxvalue"), ("splitnumber", "splitnumber")):
            v = (spec.get("range") or {}).get(yaml_k)
            if v is not None:
                g[conf_k] = _conv(v)
        _passthrough(g, spec.get("style") or {})
        _passthrough(g, spec, skip=("payload_key", "range", "style"))


def _emit_live_charts(boot, charts_cfg):
    """[[[LiveCharts]]] live_chart_items + per-chart -> per-series.

    YAML: { items: [...], show_daynight: bool, transition_angle: int,
            charts: { <chart>: { animation: bool, series: [ {obs, payload_key, style: {...}} ] } } }.
    """
    if not charts_cfg:
        boot.pop("LiveCharts", None)
        return
    s = _replace_section(boot, "LiveCharts")
    charts = charts_cfg.get("charts") or {}
    items = charts_cfg.get("items") or list(charts.keys())
    s["live_chart_items"] = [str(x) for x in items]
    _passthrough(s, charts_cfg, skip=("items", "charts"))
    for chart_name, chart_spec in charts.items():
        c = s.setdefault(chart_name, {})
        _passthrough(c, chart_spec, skip=("series",))
        for entry in (chart_spec.get("series") or []):
            name = entry.get("obs") or entry.get("name")
            if not name:
                continue
            sec = c.setdefault(name, {})
            if "payload_key" in entry:
                sec["payload_key"] = str(entry["payload_key"])
            _passthrough(sec, entry.get("style") or {})
            _passthrough(sec, entry, skip=("obs", "name", "payload_key", "style"))


def _emit_image_plots(boot, plots_cfg):
    """[[[ImageGenerator]]] -> [[[[<timespan>_images]]]] -> per-plot subsections.

    YAML: { common: {daynight_*_color, ...},
            day|week|month|year: { style: {line_type, marker_*, aggregate_interval},
                                   items: { <plot>: { yscale, series: [obs | {obs, ...}] } } } }.
    """
    if not plots_cfg:
        boot.pop("ImageGenerator", None)
        return
    s = _replace_section(boot, "ImageGenerator")
    _passthrough(s, plots_cfg.get("common") or {})
    for timespan in ("day", "week", "month", "year"):
        t_cfg = plots_cfg.get(timespan)
        if not t_cfg:
            continue
        ts = s.setdefault(f"{timespan}_images", {})
        items = t_cfg.get("items") or {}
        if items:
            ts["image_items"] = [str(k) for k in items.keys()]
        _passthrough(ts, t_cfg.get("style") or {})
        _passthrough(ts, t_cfg, skip=("items", "style"))
        for plot_name, plot_spec in items.items():
            p = ts.setdefault(plot_name, {})
            if "yscale" in plot_spec:
                p["yscale"] = _conv(plot_spec["yscale"])
            _passthrough(p, plot_spec.get("style") or {})
            _passthrough(p, plot_spec, skip=("yscale", "series", "style"))
            for series in (plot_spec.get("series") or []):
                if isinstance(series, str):
                    p.setdefault(series, {})
                else:
                    name = series.get("obs") or series.get("name")
                    if not name:
                        continue
                    sec = p.setdefault(name, {})
                    _passthrough(sec, series, skip=("obs", "name"))


DASHBOARD_SUBSECTIONS = ("Navigation", "StationInfo", "Stats", "HistoryReport",
                         "News", "LiveGauges", "LiveCharts", "ImageGenerator",
                         "CopyGenerator")


def _emit_copy(boot, copy_cfg):
    """[[[CopyGenerator]]] copy_always / copy_once (lists of file globs)."""
    if not copy_cfg:
        boot.pop("CopyGenerator", None)
        return
    s = _replace_section(boot, "CopyGenerator")
    if "always" in copy_cfg:
        s["copy_always"] = [str(x) for x in copy_cfg["always"]]
    if "once" in copy_cfg:
        s["copy_once"] = [str(x) for x in copy_cfg["once"]]


# ─── branding (user-provided files copied into the skin) ──────────────────

BRANDING_TARGETS = {
    # key in station.yaml.branding -> destination path in the skin
    "logo":                lambda src: os.path.join(SKIN_DIR, "images", os.path.basename(src)),
    "about_page":          lambda _:   os.path.join(SKIN_DIR, "about.html.tmpl"),
    "nav_fragment":        lambda _:   os.path.join(SKIN_DIR, "nav.html.inc"),
    "footer_fragment":     lambda _:   os.path.join(SKIN_DIR, "foot.html.inc"),
    "livegauges_fragment": lambda _:   os.path.join(SKIN_DIR, "livegauges.html.inc"),
}


def _branding_copy(rel_path, dst_path, label):
    # Tolerate the "branding/" prefix users naturally write (paths in YAML look
    # relative to the project root, even though we read from /branding/).
    if rel_path.startswith("branding/"):
        rel_path = rel_path[len("branding/"):]
    src = os.path.join(BRANDING_DIR, rel_path)
    if not os.path.isfile(src):
        sys.exit(f"branding.{label}: file not found at ./branding/{rel_path}")
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    shutil.copy2(src, dst_path)
    print(f"Branded {label}: {src} -> {dst_path}")


def apply_branding(branding):
    """Copy user-provided files from ./branding/ into the fuzzy-archer skin.

    Re-runs overwrite (idempotent for the files listed in YAML). Removing a key
    does NOT restore the skin's original file (the upstream copy was overwritten
    in /data) -- to revert, remove the file and let a fresh ./data seed re-seed
    the skin from /opt/station. site_name / site_url are informational only;
    the skin doesn't read them, but a user's own HTML fragments can.
    """
    if not branding:
        return
    for key, dst_fn in BRANDING_TARGETS.items():
        src_rel = branding.get(key)
        if src_rel:
            _branding_copy(src_rel, dst_fn(src_rel), key)
    for img_path in (branding.get("images") or []):
        _branding_copy(img_path, os.path.join(SKIN_DIR, "images", os.path.basename(img_path)),
                       f"images/{os.path.basename(img_path)}")


# ─── logging ([Logging] section) ───────────────────────────────────────────

def apply_logging(c, logging_cfg):
    """[Logging]: handlers + formatters + root config.

    Absent  -> restore the default (root: handlers=console, level=INFO; no extras).
    Present -> replace [Logging] entirely with the YAML content (so removing a
               handler from YAML removes it from the conf -- fully idempotent).
    """
    log = c.setdefault("Logging", {})
    log.clear()

    if not logging_cfg:
        # Default: just console at INFO (what the image's baked template carries).
        log["root"] = {"level": "INFO", "handlers": ["console"]}
        return

    for key in ("root", "handlers", "formatters"):
        sub = logging_cfg.get(key)
        if not sub:
            continue
        if key == "root":
            log["root"] = {}
            for k, v in sub.items():
                log["root"][k] = _conv(v)
        else:
            log[key] = {}
            for name, spec in sub.items():
                s = log[key].setdefault(name, {})
                for k, v in (spec or {}).items():
                    s[k] = _conv(v)


# ─── extra services + user-provided modules ────────────────────────────────

def apply_services(c, services_cfg):
    """Add user *_services entries + copy ./user/*.py modules into the skin.

    YAML: { prep: [...], data: [...], restful: [...] }.
    Absent -> no module copy, no entry adds (the publish/extra_obs entries
              that other handlers maintain still apply).
    Present -> for each entry, ensure_in_list into the matching *_services AND
              copy every .py file in ./user/ into /data/bin/user/. One-way copy:
              removing a file from ./user/ does NOT remove it from /data/bin/user/
              (rm by hand or rebuild ./data to clean up).
    """
    if not services_cfg:
        return

    # Copy user modules so the entries below can resolve.
    if os.path.isdir(USER_DIR_SRC):
        os.makedirs(USER_DIR, exist_ok=True)
        for fname in os.listdir(USER_DIR_SRC):
            src = os.path.join(USER_DIR_SRC, fname)
            if os.path.isfile(src) and fname.endswith(".py"):
                dst = os.path.join(USER_DIR, fname)
                shutil.copy2(src, dst)
                print(f"User module: {src} -> {dst}")

    svc = c.setdefault("Engine", {}).setdefault("Services", {})
    for yaml_key, conf_key in (("prep",    "prep_services"),
                               ("data",    "data_services"),
                               ("restful", "restful_services")):
        for entry in (services_cfg.get(yaml_key) or []):
            ensure_in_list(svc, conf_key, str(entry))


def apply_dashboard(c, dashboard):
    """Emit [StdReport][[Bootstrap]] subsections from station.yaml's `dashboard:` block.

    Idempotent: each helper removes its subsection when its YAML key is absent,
    so reruns always reflect the current YAML (no stale overrides). When the
    entire `dashboard:` is absent, all dashboard-managed subsections are removed
    and fuzzy-archer's skin.conf defaults apply.
    """
    boot = c.setdefault("StdReport", {}).setdefault("Bootstrap", {})
    if not dashboard:
        for name in DASHBOARD_SUBSECTIONS:
            boot.pop(name, None)
        return
    _items_section(boot, "Navigation",  "navigation_items",   dashboard.get("navigation"))
    _items_section(boot, "StationInfo", "station_info_items", dashboard.get("station_info"))
    _emit_stats(boot,        dashboard.get("stats"))
    _emit_history(boot,      dashboard.get("history"))
    _emit_news(boot,         dashboard.get("news"))
    _emit_live_gauges(boot,  dashboard.get("live_gauges"))
    _emit_live_charts(boot,  dashboard.get("live_charts"))
    _emit_image_plots(boot,  dashboard.get("image_plots"))
    _emit_copy(boot,         dashboard.get("copy"))


def apply_skin(yml):
    """skin.conf: live-gauge WebSocket URL + dashboard creds for the browser."""
    ws_url = WS_URL_ENV or str((yml.get("mqtt") or {}).get("websocket_url") or "ws://localhost:9001")
    s = configobj.ConfigObj(SKIN, file_error=True)
    jg = s.setdefault("JSONGenerator", {})
    jg["enabled"] = "true"
    conns = jg.setdefault("MQTT", {}).setdefault("connections", {})
    conns.clear()
    conns["local_broker"] = {
        "broker_connection": ws_url,
        "topics": {"weather/loop": {"type": "JSON"}},
    }
    # Read-only dashboard account. NOTE: these creds are embedded in the public
    # weewxData.json, so the account must stay read-only and scoped (see acl).
    if MQTT_DASH_PASS:
        conns["local_broker"]["mqtt_username"] = MQTT_DASH_USER
        conns["local_broker"]["mqtt_password"] = MQTT_DASH_PASS
    s.write()
    print("Patched", SKIN, "-> broker", ws_url)


def patch_jsonengine():
    """Two in-place patches to the installed fuzzy-archer jsonengine.py:

      1. convert() called with a bare string instead of a ValueTuple raises
         "string index out of range" whenever Station altitude is in 'foot'.
      2. On an empty archive database (fresh start, before the first archive
         record) lastGoodStamp is None and `lastGoodStamp - 1` raises
         TypeError. The Cheetah generator skips this case gracefully
         ("cannot find start time"); make JSONGenerator do the same.

    Warns loudly if a target moves upstream (so a maintainer notices).
    """
    path = "/data/bin/user/jsonengine.py"
    patches = [
        (
            "altitude convert bug",
            "altitude_m = convert(altitude[0], 'meter')[0]",
            "altitude_m = convert((float(altitude[0]), 'foot', 'group_altitude'), 'meter')[0]",
        ),
        (
            "empty-database guard",
            "            if enabled:\n                self.setup()\n                self.gen_data()",
            "            if enabled:\n"
            "                if self.db_binder.get_manager().lastGoodStamp() is None:\n"
            "                    log.info('JSONGenerator: empty archive database, skipping until data arrives')\n"
            "                    return\n"
            "                self.setup()\n"
            "                self.gen_data()",
        ),
    ]
    with open(path) as f:
        src = f.read()
    for label, old, new in patches:
        if new in src:
            continue
        if old in src:
            src = src.replace(old, new)
            print("Patched", path, f"({label})")
        else:
            print(f"WARNING: {path} ({label}): patch target not found; "
                  "fuzzy-archer may have changed upstream -- review configure.py.",
                  file=sys.stderr)
    with open(path, "w") as f:
        f.write(src)


# ─── main ──────────────────────────────────────────────────────────────────

def main():
    yml = load_yaml(STATION_YAML)

    c = configobj.ConfigObj(CONF, file_error=True)

    apply_station(c, yml.get("station") or {})
    # Observations + custom unit groups must register IN-PROCESS before
    # apply_mqtt_and_sensors validates user-set `units:` on sensor fields against
    # weewx.units.obs_group_dict / conversionDict.
    extra_obs_present = apply_observations(
        yml.get("observations") or [],
        (yml.get("units") or {}).get("custom_groups") or {},
    )
    apply_extra_obs_service(c, extra_obs_present)
    apply_mqtt_and_sensors(c, yml.get("mqtt") or {}, yml.get("sensors") or {})
    apply_credentials(c)
    apply_qc(c, yml.get("qc") or {})
    apply_units(c, yml.get("units") or {})
    apply_labels(c, yml.get("labels") or {})
    apply_schema(c, yml.get("schema") or {})

    apply_reports(c)
    apply_dashboard(c, yml.get("dashboard") or {})
    apply_branding(yml.get("branding") or {})
    apply_logging(c, yml.get("logging") or {})
    apply_services(c, yml.get("services") or {})

    c.write()
    print("Patched", CONF, f"(station_type = {c['Station']['station_type']})")

    apply_skin(yml)
    patch_jsonengine()


if __name__ == "__main__":
    main()
