#!/usr/bin/env python3
"""Compile station.yaml into weewx.conf + skin.conf + generated user/*.py modules.

Run inside the weewx container; configobj/yaml/weewx are baked in:

    docker compose run --rm --entrypoint python weewx /configure.py

Reads:
  /station.yaml  (the one source of configurable truth; secrets stay in .env)

Writes:
  /data/weewx.conf
  /data/skins/Bootstrap/skin.conf
  /data/bin/user/extra_obs.py     (only if `observations:` / `units.custom_groups:` set)
  /data/bin/user/extra_schema.py  (only if `schema:` set)

Env overrides (overlay-controlled, not user-edited config):
  WEEWX_DRIVER     (mqtt | simulator)        — set by docker-compose.demo.yml
  WEEWX_WS_URL     (ws/wss URL)              — set by prod overlay to wss://$DOMAIN
  MQTT_WEEWX_USER  MQTT_WEEWX_PASS           — broker creds for driver + publish
  MQTT_DASH_USER   MQTT_DASH_PASS            — read-only creds embedded in skin

The file is organised as one `apply_<section>(...)` per top-level YAML key,
called from `main()`. Phase 2/3 will plug in `apply_dashboard`, `apply_branding`,
`apply_logging`, `apply_services` -- the data flow is the same shape.
"""
import os
import sys

import configobj
import yaml
import weewx.units

CONF = "/data/weewx.conf"
SKIN = "/data/skins/Bootstrap/skin.conf"
USER_DIR = "/data/bin/user"
EXTRA_OBS = os.path.join(USER_DIR, "extra_obs.py")
EXTRA_SCHEMA = os.path.join(USER_DIR, "extra_schema.py")

STATION_YAML = os.environ.get("STATION_YAML", "/station.yaml")
USE_SIMULATOR = os.environ.get("WEEWX_DRIVER", "mqtt").strip().lower() in ("simulator", "sim")
# WEEWX_WS_URL (overlay-controlled) wins over station.yaml's mqtt.websocket_url.
WS_URL_ENV = os.environ.get("WEEWX_WS_URL", "").strip()
MQTT_WEEWX_USER = os.environ.get("MQTT_WEEWX_USER", "")
MQTT_WEEWX_PASS = os.environ.get("MQTT_WEEWX_PASS", "")
MQTT_DASH_USER = os.environ.get("MQTT_DASH_USER", "")
MQTT_DASH_PASS = os.environ.get("MQTT_DASH_PASS", "")

GENERATED_HEADER = (
    "# Generated by configure.py from station.yaml -- DO NOT EDIT BY HAND.\n"
    "# Re-running configure.py (or `./setup.sh` on a fresh ./data) regenerates it.\n"
)


# ─── small helpers ──────────────────────────────────────────────────────────

def load_yaml(path):
    try:
        with open(path) as h:
            return yaml.safe_load(h) or {}
    except FileNotFoundError:
        sys.exit(f"configure.py: station.yaml not found at {path}")


def ensure_in_list(section, key, value):
    """Make sure `value` is in a configobj list-or-scalar option."""
    cur = section.get(key, [])
    if isinstance(cur, str):
        cur = [cur] if cur else []
    else:
        cur = list(cur)
    if value not in cur:
        cur.append(value)
    section[key] = cur


def remove_from_list(section, key, value):
    """Remove `value` from a configobj list-or-scalar option, if present."""
    cur = section.get(key, [])
    if isinstance(cur, str):
        cur = [cur] if cur else []
    else:
        cur = list(cur)
    section[key] = [v for v in cur if v != value]


def remove_if_exists(path):
    if os.path.exists(path):
        os.remove(path)


# ─── section handlers ──────────────────────────────────────────────────────

def apply_station(c, station):
    """[Station] + [StdArchive]: identity + interval. Driver picked by env (demo overlay)."""
    s = c.setdefault("Station", {})
    s["location"] = str(station.get("location", "Sailing Center"))
    s["latitude"] = str(station.get("latitude", "37.808"))
    s["longitude"] = str(station.get("longitude", "-122.409"))
    alt = station.get("altitude") or {"value": 3, "unit": "foot"}
    # Written as a configobj list `3, foot` (NOT a quoted string -- StdQC and
    # WeeWX's parser handle the list form correctly).
    s["altitude"] = [str(alt.get("value", 3)), str(alt.get("unit", "foot"))]
    # Demo overlay sets WEEWX_DRIVER=simulator; default = real MQTTSubscribe driver.
    s["station_type"] = "Simulator" if USE_SIMULATOR else "MQTTSubscribeDriver"

    arc = c.setdefault("StdArchive", {})
    arc["archive_interval"] = str(station.get("archive_interval", 60))
    arc["record_generation"] = "software"


def apply_mqtt_and_sensors(c, mqtt_cfg, sensors_cfg):
    """[MQTTPublish] (loop -> weather/loop) + [MQTTSubscribeDriver] (rtl_433 ingest).

    Combined so both can share the broker host/port without ordering coupling.
    """
    broker = str(mqtt_cfg.get("broker", "mqtt"))
    port = str(mqtt_cfg.get("port", 1883))

    # [MQTTPublish]: stream every loop packet as JSON to weather/loop. The
    # default unit_system + append_unit_label produce gauge-ready keys
    # (outTemp_F, windSpeed_mph, ...) matching the fuzzy-archer skin.
    c["MQTTPublish"] = {
        "enable": "true",
        "host": broker,
        "port": port,
        "protocol": "MQTTv311",
        "topics": {
            "weather/loop": {
                "publish": "true",
                "type": "json",
                "binding": "loop",
                "unit_system": "US",
                "append_unit_label": "true",
            },
        },
    }

    # [MQTTSubscribeDriver]: translate sensors.sources into the topics map.
    topics = {"unit_system": str(sensors_cfg.get("unit_system", "US"))}
    errors = []
    for sensor in sensors_cfg.get("sources", []) or []:
        name = sensor.get("name", "?")
        topic = sensor.get("topic")
        if not topic:
            errors.append(f"sensor '{name}': missing 'topic'")
            continue
        # Default ON: rtl_433 payloads always carry string metadata (model, mic,
        # protocol, ...) that MQTTSubscribe can't floatify and would otherwise
        # use to reject the whole message. Set `ignore_unmapped: false` to
        # process every field.
        opt_out = bool(sensor.get("ignore_unmapped", True))

        section = {"message": {"type": "json"}}
        if opt_out:
            section["ignore"] = "true"
        if sensor.get("msg_id_field"):
            section["msg_id_field"] = str(sensor["msg_id_field"])

        for field, spec in (sensor.get("fields") or {}).items():
            spec = spec or {}
            entry = {}
            if opt_out:
                entry["ignore"] = "false"          # opt this field back in
            wx_name = spec.get("name", field)
            entry["name"] = wx_name
            if "units" in spec:
                units = spec["units"]
                if units not in weewx.units.conversionDict:
                    errors.append(f"sensor '{name}', field '{field}': unknown units '{units}'")
                elif wx_name not in weewx.units.obs_group_dict:
                    errors.append(f"sensor '{name}', field '{field}': '{wx_name}' "
                                  "is not a known WeeWX observation (can't apply units)")
                else:
                    entry["units"] = units
            if spec.get("contains_total"):
                entry["contains_total"] = "true"
            section[field] = entry
        topics[topic] = section

    if errors:
        sys.exit("station.yaml sensors errors:\n  - " + "\n  - ".join(errors))

    c["MQTTSubscribeDriver"] = {
        "driver": "user.mqttsubscribe",
        "host": broker,
        "port": port,
        "topics": topics,
    }
    c.pop("MQTTSubscribeService", None)

    # Engine services: keep publish (RESTful), drop the subscribe *service*
    # entry the installer added (we use it as the DRIVER, not a service).
    svc = c.setdefault("Engine", {}).setdefault("Services", {})
    remove_from_list(svc, "data_services", "user.mqttsubscribe.MQTTSubscribeService")
    ensure_in_list(svc, "restful_services", "user.mqttpublish.PublishWeeWX")


def apply_credentials(c):
    """Wire MQTT creds from the env (.env) into driver + publish sections."""
    if MQTT_WEEWX_PASS:
        for section in ("MQTTSubscribeDriver", "MQTTPublish"):
            c[section]["username"] = MQTT_WEEWX_USER
            c[section]["password"] = MQTT_WEEWX_PASS


def apply_qc(c, qc):
    """[StdQC][[MinMax]]: per-observation min/max bounds (with optional unit).

    Values are written as configobj lists so they emit unquoted -- a quoted
    `"min, max, unit"` would be mis-parsed by StdQC at runtime.
    """
    if not qc:
        return
    mm = c.setdefault("StdQC", {}).setdefault("MinMax", {})
    for obs, bounds in qc.items():
        out = [str(bounds["min"]), str(bounds["max"])]
        if "unit" in bounds:
            out.append(str(bounds["unit"]))
        mm[obs] = out


def apply_units(c, units):
    """[StdConvert][Group]: force display unit per group.

    `custom_groups` (defining brand-new unit groups) is written into
    `extra_obs.py` instead of weewx.conf -- see apply_observations().
    """
    if not units:
        return
    groups = units.get("groups") or {}
    if groups:
        g = c.setdefault("StdConvert", {}).setdefault("Group", {})
        for grp, unit in groups.items():
            g[grp] = str(unit)


def apply_labels(c, labels):
    """[Labels][Generic]: per-observation display label overrides."""
    if not labels:
        return
    lab = c.setdefault("Labels", {}).setdefault("Generic", {})
    for obs, label in labels.items():
        lab[obs] = str(label)


def apply_observations(observations, custom_groups):
    """Write user/extra_obs.py registering obs_group_dict + (optional) custom unit groups.

    Returns True if a service entry should be wired (always True when present).
    """
    if not observations and not custom_groups:
        remove_if_exists(EXTRA_OBS)
        return False

    lines = [GENERATED_HEADER,
             "import weewx.units\n",
             "from weewx.engine import StdService\n",
             "\n"]
    # Custom unit groups first (so per-obs registrations below can reference them).
    for grp, units in (custom_groups or {}).items():
        # units may be a dict {US: dBm, Metric: dBm, MetricWX: dBm} or a single str.
        if isinstance(units, str):
            units = {"US": units, "Metric": units, "MetricWX": units}
        for system, unit in units.items():
            sys_map = {"US": "USUnits", "Metric": "MetricUnits", "MetricWX": "MetricWXUnits"}[system]
            lines.append(f"weewx.units.{sys_map}[{grp!r}] = {unit!r}\n")
    for obs in observations or []:
        lines.append(
            f"weewx.units.obs_group_dict[{obs['name']!r}] = {obs['group']!r}\n"
        )
    # Tiny no-op StdService so weewx.conf can list it under prep_services and
    # the module gets loaded (which is what runs the registrations above).
    lines += [
        "\n",
        "class ExtraObservations(StdService):\n",
        "    \"\"\"Loader for the obs_group/unit registrations above.\"\"\"\n",
        "    def __init__(self, engine, config_dict):\n",
        "        super().__init__(engine, config_dict)\n",
    ]
    os.makedirs(USER_DIR, exist_ok=True)
    with open(EXTRA_OBS, "w") as f:
        f.writelines(lines)
    return True


def apply_extra_obs_service(c, enable):
    """Wire user.extra_obs.ExtraObservations into prep_services (or remove it)."""
    svc = c.setdefault("Engine", {}).setdefault("Services", {})
    if enable:
        ensure_in_list(svc, "prep_services", "user.extra_obs.ExtraObservations")
    else:
        remove_from_list(svc, "prep_services", "user.extra_obs.ExtraObservations")


def apply_schema(c, schema_cfg):
    """Optional custom DB schema. Generates user/extra_schema.py = base + extras."""
    if not schema_cfg:
        remove_if_exists(EXTRA_SCHEMA)
        # Reset binding to the stock schema if a previous run had pointed it at extra_schema.
        b = c.setdefault("DataBindings", {}).setdefault("wx_binding", {})
        if b.get("schema", "").startswith("user.extra_schema"):
            b["schema"] = "schemas.wview_extended.schema"
        return

    base = str(schema_cfg.get("extends", "wview_extended"))
    extras = list(schema_cfg.get("extra_columns") or [])
    if not extras:
        sys.exit("station.yaml schema: extra_columns must be a non-empty list (omit `schema:` to use the stock schema)")

    lines = [GENERATED_HEADER,
             f"# Extends weewx's built-in `{base}` schema with the columns below.\n",
             "\n",
             f"from schemas.{base} import table as _base_table, day_summaries as _base_summaries\n",
             "\n",
             "_extras = [\n"]
    for col in extras:
        lines.append(f"    ({col!r}, 'REAL'),\n")
    lines += [
        "]\n",
        "\n",
        "table = list(_base_table) + _extras\n",
        "day_summaries = list(_base_summaries) + [(c[0], 'scalar') for c in _extras]\n",
        "schema = {'table': table, 'day_summaries': day_summaries}\n",
    ]
    os.makedirs(USER_DIR, exist_ok=True)
    with open(EXTRA_SCHEMA, "w") as f:
        f.writelines(lines)
    # Point the default binding at the generated module.
    c.setdefault("DataBindings", {}).setdefault("wx_binding", {})["schema"] = "user.extra_schema.schema"


def apply_reports(c):
    """[StdReport]: enable only fuzzy-archer (Bootstrap), into public_html."""
    rep = c.setdefault("StdReport", {})
    rep["HTML_ROOT"] = "public_html"
    for _name, sec in list(rep.items()):
        if isinstance(sec, dict) and sec.get("skin") in ("Seasons", "Standard"):
            sec["enable"] = "false"
    boot = rep.setdefault("Bootstrap", {})
    boot["skin"] = "Bootstrap"
    boot["enable"] = "true"
    boot["lang"] = "en"
    boot["HTML_ROOT"] = "public_html"


def apply_skin(yml):
    """skin.conf: live-gauge WebSocket URL + dashboard creds for the browser."""
    ws_url = WS_URL_ENV or str((yml.get("mqtt") or {}).get("websocket_url") or "ws://localhost:9001")
    s = configobj.ConfigObj(SKIN, file_error=True)
    jg = s.setdefault("JSONGenerator", {})
    jg["enabled"] = "true"
    conns = jg.setdefault("MQTT", {}).setdefault("connections", {})
    conns.clear()
    conns["local_broker"] = {
        "broker_connection": ws_url,
        "topics": {"weather/loop": {"type": "JSON"}},
    }
    # Read-only dashboard account. NOTE: these creds are embedded in the public
    # weewxData.json, so the account must stay read-only and scoped (see acl).
    if MQTT_DASH_PASS:
        conns["local_broker"]["mqtt_username"] = MQTT_DASH_USER
        conns["local_broker"]["mqtt_password"] = MQTT_DASH_PASS
    s.write()
    print("Patched", SKIN, "-> broker", ws_url)


def patch_jsonengine():
    """Two in-place patches to the installed fuzzy-archer jsonengine.py:

      1. convert() called with a bare string instead of a ValueTuple raises
         "string index out of range" whenever Station altitude is in 'foot'.
      2. On an empty archive database (fresh start, before the first archive
         record) lastGoodStamp is None and `lastGoodStamp - 1` raises
         TypeError. The Cheetah generator skips this case gracefully
         ("cannot find start time"); make JSONGenerator do the same.

    Warns loudly if a target moves upstream (so a maintainer notices).
    """
    path = "/data/bin/user/jsonengine.py"
    patches = [
        (
            "altitude convert bug",
            "altitude_m = convert(altitude[0], 'meter')[0]",
            "altitude_m = convert((float(altitude[0]), 'foot', 'group_altitude'), 'meter')[0]",
        ),
        (
            "empty-database guard",
            "            if enabled:\n                self.setup()\n                self.gen_data()",
            "            if enabled:\n"
            "                if self.db_binder.get_manager().lastGoodStamp() is None:\n"
            "                    log.info('JSONGenerator: empty archive database, skipping until data arrives')\n"
            "                    return\n"
            "                self.setup()\n"
            "                self.gen_data()",
        ),
    ]
    with open(path) as f:
        src = f.read()
    for label, old, new in patches:
        if new in src:
            continue
        if old in src:
            src = src.replace(old, new)
            print("Patched", path, f"({label})")
        else:
            print(f"WARNING: {path} ({label}): patch target not found; "
                  "fuzzy-archer may have changed upstream -- review configure.py.",
                  file=sys.stderr)
    with open(path, "w") as f:
        f.write(src)


# ─── main ──────────────────────────────────────────────────────────────────

def main():
    yml = load_yaml(STATION_YAML)

    c = configobj.ConfigObj(CONF, file_error=True)

    apply_station(c, yml.get("station") or {})
    apply_mqtt_and_sensors(c, yml.get("mqtt") or {}, yml.get("sensors") or {})
    apply_credentials(c)
    apply_qc(c, yml.get("qc") or {})
    apply_units(c, yml.get("units") or {})
    apply_labels(c, yml.get("labels") or {})

    extra_obs_present = apply_observations(
        yml.get("observations") or [],
        (yml.get("units") or {}).get("custom_groups") or {},
    )
    apply_extra_obs_service(c, extra_obs_present)
    apply_schema(c, yml.get("schema") or {})

    apply_reports(c)

    c.write()
    print("Patched", CONF, f"(station_type = {c['Station']['station_type']})")

    apply_skin(yml)
    patch_jsonengine()


if __name__ == "__main__":
    main()
